<?php
/************************************************************
 * *
 *  * Copyright © Boolfly. All rights reserved.
 *  * See COPYING.txt for license details.
 *  *
 *  * @author    info@boolfly.com
 * *  @project   Quick View
 */
/**
 * @var \Boolfly\QuickView\Block\View $block
 */
?>
<script type="text/x-magento-init">
    {
        ".product-items" : {
            "boolflyQuickView": <?= /* @escapeNotVerified */ $block->getJsonData()?>
        }
    }
</script>

